# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageApiStub(object):
    """API service for client/server communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTile = channel.unary_unary(
                '/storage.StorageApi/GetTile',
                request_serializer=storage__pb2.GetTileRequest.SerializeToString,
                response_deserializer=storage__pb2.GetTileResponse.FromString,
                _registered_method=True)
        self.PutTile = channel.unary_unary(
                '/storage.StorageApi/PutTile',
                request_serializer=storage__pb2.PutTileRequest.SerializeToString,
                response_deserializer=storage__pb2.PutTileResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/storage.StorageApi/HealthCheck',
                request_serializer=storage__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=storage__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class StorageApiServicer(object):
    """API service for client/server communication
    """

    def GetTile(self, request, context):
        """Get a tile from storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutTile(self, request, context):
        """Store a tile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTile,
                    request_deserializer=storage__pb2.GetTileRequest.FromString,
                    response_serializer=storage__pb2.GetTileResponse.SerializeToString,
            ),
            'PutTile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutTile,
                    request_deserializer=storage__pb2.PutTileRequest.FromString,
                    response_serializer=storage__pb2.PutTileResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=storage__pb2.HealthCheckRequest.FromString,
                    response_serializer=storage__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageApi(object):
    """API service for client/server communication
    """

    @staticmethod
    def GetTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageApi/GetTile',
            storage__pb2.GetTileRequest.SerializeToString,
            storage__pb2.GetTileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageApi/PutTile',
            storage__pb2.PutTileRequest.SerializeToString,
            storage__pb2.PutTileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageApi/HealthCheck',
            storage__pb2.HealthCheckRequest.SerializeToString,
            storage__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
