# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"A\n\x0eGetTileRequest\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\t\n\x01x\x18\x02 \x01(\r\x12\t\n\x01y\x18\x03 \x01(\r\x12\r\n\x05level\x18\x04 \x01(\r\"\x1f\n\x0fGetTileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32J\n\nStorageApi\x12<\n\x07GetTile\x12\x17.storage.GetTileRequest\x1a\x18.storage.GetTileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTILEREQUEST']._serialized_start=26
  _globals['_GETTILEREQUEST']._serialized_end=91
  _globals['_GETTILERESPONSE']._serialized_start=93
  _globals['_GETTILERESPONSE']._serialized_end=124
  _globals['_STORAGEAPI']._serialized_start=126
  _globals['_STORAGEAPI']._serialized_end=200
# @@protoc_insertion_point(module_scope)
