apiVersion: v1
kind: Pod
metadata:
  name: dispatch
  namespace: histion
spec:
  restartPolicy: Never
  containers:
  - name: dispatch
    image: docker.io/thavlik/histion-compiler:latest
    imagePullPolicy: Always
    command:
      - histion-compiler
      - dispatch
      - --max-dispatch
      - "3"
    env:
    - name: RUST_LOG
      value: info
    - name: S3_BUCKET
      value: camelyon17
    - name: S3_PATH_PREFIX
      value: "images/"
    - name: S3_ENDPOINT
      value: https://nyc3.digitaloceanspaces.com
    - name: S3_REGION
      value: nyc3
    - name: STREAM_NAME
      value: histion
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: spaces-cred
          key: access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: spaces-cred
          key: secret_access_key
    - name: NATS_URL
      value: nats://nats.nats.svc.cluster.local:4222
    - name: POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: host
    - name: POSTGRES_PORT
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: port
    - name: POSTGRES_DATABASE
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: database
    - name: POSTGRES_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: password
    - name: POSTGRES_SSLMODE
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: sslmode
    - name: POSTGRES_CA_CERT
      valueFrom:
        secretKeyRef:
          name: postgres-cred
          key: ca
    - name: NATS_USER
      valueFrom:
        secretKeyRef:
          name: nats-cred
          key: user
    - name: NATS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nats-cred
          key: password